### ISSUE TITLE
protege-server should expose an HTTPS endpoint that serves out version-URLed instances of stored ontologies

### ISSUE THREAD

**Issue by lonniev** [protegeproject/protege-server#20]
We have a crisis in the Ontology community of crappy change management for distributed collaboration of ontologies. We need servers that change manage our ontologies so that teams can edit them. We need change-managing ontology repositories that will serve out versions of stored ontologies given an HTTPS GET request for their URL.

**Comment by tudorache** [comment]
Did you take a look at WebProtege? It has a complete and executable change management, and many other useful collaboration features.

We've been developing WebProtege specifically to support collaboration, while the Protege 5 client-server is still a new addition.

You can find out more about WebProtege here:

Docs: http://protegewiki.stanford.edu/wiki/WebProtege
Demo: http://webprotege.stanford.edu
Source: https://github.com/protegeproject/webprotege

**Comment by lonniev** [comment]
I’m aware of it and even have one or two small ontologies there but will have to revisit it to see if it has a change-managed—post-and-publish-result service.

**Comment by tudorache** [comment]
Not exactly sure what that means, but you can download from WebProtege any revision of the ontology using a http get request.

**Comment by lonniev** [comment]
Just like we can get the raw source for any file for any of its commits via GitHub, we need our ontology repositories to make their content available as HTTP GET requests. Then, the IRI that appears in an owl:import statement can be the appropriate change-controlled version from the definitive source. No duplicated files, no need for additional web services, no doubt about which file is legitimate.

In WebProtege, I’m missing the Duh, here it is URL.



In the snapshot, the IRI would ideally be automatically updated and reference the WebProtege change-controlled content.

Can I get that already there?



-- 
Lonnie VanZandt
303-900-3048

On 04 April 2016 at 18:35:26, Tania Tudorache (notifications@github.com) wrote:

Not exactly sure what that means, but you can download from WebProtege any revision of the ontology using a http get request.

**Comment by tudorache** [comment]
You can get a zip containing the top ontology (most importing), renamed to root-ontology.owl, and a cached version of all imports (with the original IRIs) from WebProtege with: 

http://webprotege.stanford.edu/download?ontology=Your_Ontology_ID&revision=Your_revision_number&format=owl

Your_Ontology_ID is the id of your ontology (you can get it from the browser address bar when browsing your ontology in WebProtege, it is the projectId argument)

For more questions on WebProtege, we should move the discussion on the mailing list (http://protege.stanford.edu/support.php).

**Comment by lonniev** [comment]
For the use case in mind, the ontology repo has to maintain an HTTP endpoint that serves files directly in response to simple HTTP or HTTPS GET requests.

The goal isn’t for a human to get a copy of some zip or pdf file but for the IRI resolvers we build into our tools to be able to obtain a copy of the ontology file just as if it was offered at an HTTP server like this one: http://individual.utoronto.ca/hesham/Ontology/IPDFull.owl

(There is so much link rot that it takes a while to find a representative example for systems that offer the actual OWL files they cite in their IRIs!)



-- 
Lonnie VanZandt
303-900-3048

On 04 April 2016 at 19:48:49, Tania Tudorache (notifications@github.com) wrote:

You can get a zip containing the top ontology (most importing), renamed to root-ontology.owl, and a cached version of all imports (with the original IRIs) from WebProtege with:

http://webprotege.stanford.edu/download?ontology=Your_Ontology_ID&revision=Your_revision_number&format=owl

Your_Ontology_ID is the id of your ontology (you can get it from the browser address bar when browsing your ontology in WebProtege, it is the projectId argument)

For more questions on WebProtege, we should move the discussion on the mailing list (http://protege.stanford.edu/support.php).

**Comment by bdionne** [comment]
This might be supportable down the road, but for now I agree that web protege might be your best bet. This project currently is focused on change management during development of an ontology. Curation and publication are downstream processes.
