### ISSUE TITLE
Committing changes to server is not thread-safe yet

### ISSUE THREAD

**Issue by johardi** [protegeproject/protege-server#23]

**Comment by bdionne** [comment]
Yes, here's a subtle [issue](https://github.com/bdionne/protege-server/commit/09cd259ea91147adf63f541079c63891dccba932) I uncovered and fixed. It creates a larger critical section, but is mitigated by storing the `HEAD` revision in the change pool. 

Here's an [integration test](https://github.com/bdionne/protege-client-server-integration-tests/blob/master/src/test/java/org/protege/editor/owl/integration/ConcurentCommitChangesTest.java) that exhibits the bug.

**Comment by johardi** [comment]
Fixed via https://github.com/protegeproject/protege-server/commit/09cd259ea91147adf63f541079c63891dccba932
