### ISSUE TITLE
Server should broadcast an event when a commit is accepted

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/protege-server#26]

**Comment by bdionne** [comment]
really? - you mean a push? Not sure I agree

**Comment by rsgoncalves** [comment]
The client needs to be made aware that remote changes occurred in order to act upon them. The use case for this is refreshing diff views, so far, though it might be handy for other things further down the line. What other approach would you suggest?

**Comment by bdionne** [comment]
I think I may have stated the issue you reference (#18) incorrectly. I was referring to the client that actually makes the commit. That client ought to be able to see them in prompt diff. 

Other clients will eventually see them when they either do an update or have autoupdate enabled

**Comment by rsgoncalves** [comment]
Currently (in the diff tab) that client cannot see any changes until they are committed and the UI refreshed. In order to signal the need for a refresh we need some event, though you're right it needn't be from the server; I could use an event local to the client to get the commit author to see the commit immediately. Other clients will get these changes in the diff UI via the ontology update listeners already in place, so that's all good.

**Comment by rsgoncalves** [comment]
continued in https://github.com/protegeproject/protege-client/issues/29
