### ISSUE TITLE
Timeouts returning 500 rather than 440

### ISSUE THREAD

**Issue by bdionne** [protegeproject/protege-server#36]
When a user session times out the client is receiving a 500. This prevents the client from prompting the user to login again. 

This [commit](https://github.com/protegeproject/protege-server/commit/6774356244d3601154b93b4309dd317088806573) removes the exception that was caught in [`AuthenticationHandler`](https://github.com/protegeproject/protege-server/blob/http-metaproject-integration/src/main/java/org/protege/editor/owl/server/http/handlers/AuthenticationHandler.java#L29). Looking at this handler, I suppose the table could return a null but that seems like an unlikely case

**Comment by johardi** [comment]
Fixed via https://github.com/protegeproject/protege-server/commit/7e4de2f48a374a5e016b962c6e0a1535f9a637df
